# Generated by Django 5.1.1 on 2024-09-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='abount',
            new_name='about',
        ),
    ]
