# Generated by Django 5.1.1 on 2024-09-30 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_abount_footer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
