# Generated by Django 5.1.1 on 2024-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footer_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='whatsapp_channel_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
