# Generated by Django 5.1.1 on 2024-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_footer_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skill5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='skill6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=10, null=True),
        ),
    ]
