# Generated by Django 5.1.1 on 2024-10-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_jobs_skill5_jobs_skill6_alter_jobs_work_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='is_approved',
        ),
    ]
