# Generated by Django 5.1.1 on 2024-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_company_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='ak_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='shanu_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
